// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmakgvgtduxtactdiwyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttYWtndmd0ZHV4dGFjdGRpd3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NDI2NzgsImV4cCI6MjA1MjMxODY3OH0.V9dLT2yaWhj1SYvlRjMRvY9r9-1XGFX7TeMBL_9xpGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);